# Generated by Django 4.2.30 on 2026-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpoints_useditemlisting_useditempurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditemlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='used_item_listings/'),
        ),
    ]
