# Generated by Django 4.2.30 on 2026-06-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useditemcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='used_item_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.useditemlisting'),
        ),
    ]
