# Generated by Django 4.2.30 on 2026-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderitem_used_item_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditemlisting',
            name='donation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useditemlisting',
            name='suggest_donation',
            field=models.BooleanField(default=False),
        ),
    ]
