# Generated by Django 4.2.30 on 2026-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_useditemlisting_donation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditemlisting',
            name='is_donation',
            field=models.BooleanField(default=False),
        ),
    ]
