# Generated by Django 4.2.30 on 2026-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_billingaddress_location_billingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditemlisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useditemlisting',
            name='yolo_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
