# Generated by Django 4.2.30 on 2026-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_useditemlisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditemlisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='used_item_videos/'),
        ),
    ]
